### ISSUE TITLE
Use of Structure<T>

### ISSUE THREAD

**Issue by yonaskolb** [AttilaTheFun/SwaggerParser#16]
Is there any reason that not all top level spec properties use Structure\<T\>, for example: 
- `let securityDefinitions: [String : SecuritySchema]` 
- `let paths: [String : Path]`

**Comment by AttilaTheFun** [comment]
The point of the 'Structure' type was to unify references to the same named type. In the case of parameters, responses, and definitions, the named types are the reusable, model, parameter, and response types. E.g., an 'Offset' and a 'Limit' parameter or a 'User' model. I guess it could make sense for security definitions, but they're not referenced with the $ref semantics. Rather, the security requirements just reference the name and a set of scopes. Basically, my feeling was that the Structure<T> was for named types that, when defined at the top level scope could be used to generate strictly typed objects, and then referenced elsewhere in code. Does this answer your question?

**Comment by yonaskolb** [comment]
Yeah, makes sense, fair enough.
I guess it's a balance between consistency in the public API and consistency in how those types are used internally.
In my mind all these properties would actually be dictionaries at the top level, as that's more idiomatic and how groups of named things are usually typed in Swift, and keep Structure as an internal thing.

My 2 cents, happy however it is.

**Comment by AttilaTheFun** [comment]
That's a good point, actually. I think having a consistent API is important. The point of the 'Structure' type was more to copy the name + schema of resolved references so that when you're writing a template, you don't have to 'look up' the definition every time. But at the top level, it makes sense to offer a more idiomatic interpretation of the definitions, parameters etc. I'll try to bundle these changes with your metadata extraction PR and tag that as 0.4.0 because it's a breaking API change.

Regarding versioning, I feel that pre-1.0, minor version bumps can be API-breaking and patch bumps can be additive to the api / fix bugs. Post 1.0, breaking API changes need to increment the major version number, additive changes must bump the minor version number, and bug fixes / implementation improvements can just bump the patch number. Does that seem reasonable?

**Comment by AttilaTheFun** [comment]
@yonaskolb I just pushed https://github.com/AttilaTheFun/SwaggerParser/commit/93936c3a2ba2874d14914d21b36c5d5e620bbfc4
It makes the top level interface consistently use dictionaries per your suggestion. It will be included with your metadata change and my reference resolver PR in 0.4.0
